site_name: LeetCode Solutions
site_url: https://leetcode.romitsagu.com
repo_name: NinePiece2/Leetcode
repo_url: https://github.com/NinePiece2/Leetcode
copyright: Copyright © 2025 Romit Sagu

docs_dir: docs

theme:
  name: material
  language: en
  font:
    text: Poppins
    code: Fira Code
  icon:
      repo: fontawesome/brands/github
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - toggle.dark_mode
    - content.code.copy
    - content.tabs

extra_css:
  - overrides.css

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

nav:
  - Overview: README.md