site_name: LeetCode Solutions
site_url: https://leetcode.romitsagu.com
repo_name: NinePiece2/Leetcode
repo_url: https://github.com/NinePiece2/Leetcode
copyright: Copyright © 2025 Romit Sagu

docs_dir: docs

theme:
  name: material
  language: en
  font:
    text: Poppins
    code: Fira Code
  icon:
    repo: fontawesome/brands/github
    logo: material/code-braces
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - toggle.dark_mode
    - content.code.select
    - announce.dismiss
    - content.code.copy
    - content.action.edit
    - content.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://GitHub.com/NinePiece2
    - icon: fontawesome/brands/linkedin
      link: https://Linkedin.com/in/romit-sagu

extra_css:
  - overrides.css

extra_javascript:
  - custom.js

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      toc_depth: 0

nav:
  - Overview: README.md