name: Update LeetCode Grid

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Sync Leetcode"]
    types:
      - completed

jobs:
  update-readme:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Check for Solutions/ changes
        id: changes
        run: |
          git fetch --depth=2 origin ${{ github.ref_name }}
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            # Normal commit (has a parent)
            git diff --name-only HEAD^ HEAD > files.txt
          else
            # Root commit (no parent)
            git show --name-only --pretty="" HEAD > files.txt
          fi

          if grep -q '^Solutions/' files.txt; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Python
        if: steps.changes.outputs.changed == 'true'
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        if: steps.changes.outputs.changed == 'true'
        run: |
          pip install pyyaml requests

      - name: Restore LeetCode API cache
        if: steps.changes.outputs.changed == 'true'
        uses: actions/cache@v4
        with:
          path: .leetcode_cache.json
          key: leetcode-cache

      - name: Generate LeetCode README table
        if: steps.changes.outputs.changed == 'true'
        run: |
          python ./Scripts/update_project_readme.py

      - name: Save updated cache
        if: always() && steps.changes.outputs.changed == 'true'
        uses: actions/cache/save@v4
        with:
          path: .leetcode_cache.json
          key: leetcode-cache

      - name: Commit and push changes
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          git add README.md Site_README.md
          git diff-index --quiet HEAD || git commit -m "[Auto] Update LeetCode README table"

          git fetch origin ${{ github.ref_name }}
          git rebase origin/${{ github.ref_name }}

          git push origin HEAD:${{ github.ref_name }}